Update build-and-release-yourself.yml

diff --git a/.github/workflows/build-and-release-yourself.yml b/.github/workflows/build-and-release-yourself.yml
--- a/.github/workflows/build-and-release-yourself.yml
+++ b/.github/workflows/build-and-release-yourself.yml
@@ -45,14 +45,8 @@ jobs:
           fi
 
       - name: Download and Validate Tweak
-        run: | 
-        echo "Downloading from: ${{ inputs.tweak_url }}"
-          wget "${{ inputs.tweak_url }}" --no-verbose -O ${{ github.workspace }}/eeveespotify.deb
-          file_type=$(file --mime-type -b ${{ github.workspace }}/eeveespotify.deb)
-          if [ "$file_type" != "application/vnd.debian.binary-package" ]; then
-            echo "::error::Validation failed: The file is not a valid DEB file. Detected type: $file_type."
-            exit 1
-          fi
+        run: |
+        wget "${{ inputs.tweak_url }}" --no-verbose -O "${{ github.workspace }}/eeveespotify.deb" && file_type=$(file --mime-type -b "${{ github.workspace }}/eeveespotify.deb") && if [ "$file_type" != "application/vnd.debian.binary-package" ]; then echo "Validation failed: The file is not a valid DEB file. Detected type: $file_type."; exit 1; fi
 
       - name: Download SwiftProtobuf
         run: |
